### ISSUE TITLE
Because shorebird_cli depends on googleapis_auth ^1.6.0 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by FlowerMiLeLe** [shorebirdtech/shorebird#2047] opened 2024-05-09 03:09 UTC
Big guy, hello, let me first talk about the use problem I encountered:
What the picture shows:
![Snip20240509_5](https://github.com/shorebirdtech/shorebird/assets/169323688/ac08b998-d39a-44d3-972a-909e632d497b)
My version of flutter uses 3.16.0, but I ran into the problem googleapis_auth ^1.6.0, I thought it was my version of flutter that should use 3.19.5, I switched to 3.19.5, this problem still occurs, I don't know how to solve it.
Please give me some advice and let me solve this problem.
Finally: Shorebird library is the most awesome, the world's most handsome Shorebird.

==============
大佬，你好，我先说我遇到的使用问题： 
图片所展示的： 
![Snip20240509_5](https://github.com/shorebirdtech/shorebird/assets/169323688/ac08b998-d39a-44d3-972a-909e632d497b)

我的flutter版本使用的是3.16.0，但我遇到了googleapis_auth ^1.6.0这个问题，我以为是我得flutter版本应该使用3.19.5，我切换到3.19.5，仍然出现这个问题，我不知道该怎么解决。 
请大佬给我点意见，让我解决这个问题。 
最后：Shorebird库最牛逼，全世界Shorebird最帅。

**Comment by FlowerMiLeLe** [comment] 2024-05-09 05:21
This is my flutter configuration and mirroring。
====
这是我的flutter配置和镜像 
![Snip20240509_8](https://github.com/shorebirdtech/shorebird/assets/169323688/a625534d-9fa3-413e-8705-0197e2312b70)

This is my flutter doctor
========
这是我的flutter doctor
![Snip20240509_9](https://github.com/shorebirdtech/shorebird/assets/169323688/8b2bf446-0b88-4f74-ac1e-a8a007c5d358)

**Comment by eseidel** [comment] 2024-05-09 17:28
This seems very similar to https://github.com/shorebirdtech/shorebird/issues/1938 and possibly https://github.com/shorebirdtech/shorebird/issues/1944

**Comment by FlowerMiLeLe** [comment] 2024-05-10 01:26
> [这看起来与#1938](https://github.com/shorebirdtech/shorebird/issues/1938)和可能#1944非常相似[](https://github.com/shorebirdtech/shorebird/issues/1944)

Ok, I looked at the Big Guy you have to recommend link, but I still don't know how to solve this problem.
========
好的，我看了下大佬你得推荐链接，但我仍然不知道该怎么解决这个问题。

**Comment by eseidel** [comment] 2024-05-17 17:23
So far I believe this has only happened for individuals using `PUB_HOSTED_URL`.  I wonder if there could be a bug in `pub` itself.

Please let me know if anyone is seeing this and is not using `PUB_HOSTED_URL`.

**Comment by getsemanivdmn** [comment] 2024-05-21 09:27
> > [这看起来与#1938](https://github.com/shorebirdtech/shorebird/issues/1938)和可能#1944非常相似
> 
> # Ok, I looked at the Big Guy you have to recommend link, but I still don't know how to solve this problem.
> 好的，我看了下大佬你得推荐链接，但我仍然不知道该怎么解决这个问题。

你好请问你解决了吗 我也遇到这个问题了

**Comment by getsemanivdmn** [comment] 2024-05-22 01:17
你好请问你的问题解决了吗 我也遇到了同样的问题

**Comment by FlowerMiLeLe** [comment] 2024-05-29 01:55
> 你好请问你的问题解决了吗我也遇到了同样的问题

我还没解决这个问题，我现在只是在学习这个库，还没有投入到正式项目中
====
I haven't solved the problem yet, I'm just learning about the library and haven't put it into a formal project yet

**Comment by FlowerMiLeLe** [comment] 2024-05-29 05:35
哈哈哈哈，问题解决了，是镜像的原因！和shorbird库没有问题。
========
Ha ha ha, problem solved, it's the mirror! No problem with shorbird library.

![Snip20240529_73](https://github.com/shorebirdtech/shorebird/assets/169323688/9423e200-98e4-4bb7-9fcd-6d97a4fe7ea3)

**Comment by FlowerMiLeLe** [comment] 2024-05-29 05:36
> 你好请问你的问题解决了吗 我也遇到了同样的问题

问题解决了，是镜像的原因

**Comment by eseidel** [comment] 2024-05-29 16:30
"The problem is solved it was the mirror"

Thank you for letting us know!

**Comment by bryanoltman** [comment] 2024-05-29 17:35
I think this is is resolved? Closing, please reopen if I'm incorrect.

**Closed as completed by bryanoltman** 2024-05-29 17:35 UTC
