### ISSUE TITLE
Customer seeing `shorebird preview` hang at "Using production track..."

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1504] opened 2023-11-16 04:42 UTC
I suspect this is a download issue?  The customer reports being in South Korea.  I would expect South Korea to reach Google Storage no problem:
https://discord.com/channels/1030243211995791380/1125516353370075306/1173897598579527740

**Comment by eseidel** [comment] 2023-11-16 04:45
Customer support thread: https://discord.com/channels/1030243211995791380/1174569116875628574

**Comment by bryanoltman** [comment] 2023-11-21 16:33
It looks like this resolved and was specific to a given release. There is likely some kind of bug here, but I'm not sure how we would go about reproducing it. Going to close this for now until it pops up again.

**Closed as completed by bryanoltman** 2023-11-21 16:33 UTC
