### ISSUE TITLE
fix: `shorebird preview` shows old logs on Android

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1479] opened 2023-11-10 21:54 UTC
I thought I already filed this, but maybe not.

Flutter has some code to avoid this:
https://github.com/flutter/flutter/blob/a6aaad348752145c4e3766bc5a859a15a0922f7f/packages/flutter_tools/lib/src/android/android_device.dart#L1016

**Comment by bryanoltman** [comment] 2023-11-10 22:08
Closing as duplicate of https://github.com/shorebirdtech/shorebird/issues/1417

**Closed as completed by bryanoltman** 2023-11-10 22:08 UTC
Labels: enhancement
