### ISSUE TITLE
SHOREBIRD_TOKEN Not working?

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2454] opened 2024-08-28 20:20 UTC
From @rafaelfernandesx:

I did some more tests now using --verbose and it returns this error:
<img width="1046" alt="image" src="https://github.com/user-attachments/assets/12c83c61-e9ec-4038-bab7-66f78108db1e">

Remembering that my authentication is with the Microsoft account, it seems that it is authenticating with Google, but I don't know if it is the same authentication.

this is the local and codemagic version of shorebird:
1.2.2 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.24.1 • revision 01eadfbfbbe78b64aed76ea9f422eb432fd339cb
Engine • revision 8978a5e50daa39aa1180d57c7ec991e787d7f545

_Originally posted by @rafaelfernandesx in https://github.com/shorebirdtech/shorebird/issues/1808#issuecomment-2316016893_

**Comment by eseidel** [comment] 2024-08-28 20:21
Sounds like they believe that SHOREBIRD_TOKEN might be assuming Google even though they have a microsoft account?

**Comment by eseidel** [comment] 2024-08-28 20:24
Our guess @rafaelfernandesx is that the SHOREBIRD_TOKEN isn't properly getting updated in the CI.  Are you certain that it's being changed?

**Comment by bryanoltman** [comment] 2024-08-28 20:28
@rafaelfernandesx you mentioned in the other comment that you're base-64 encoding the token. You should not do this—the token is already encoded.

**Comment by felangel** [comment] 2024-08-28 20:29
@rafaelfernandesx  does this happen if you re-generate the CI token using the latest version of shorebird_cli?

**Comment by bryanoltman** [comment] 2024-08-28 20:31
Nope, just verified that generating a Microsoft token and setting it as an env variable as per the instructions does not print the warning displayed in the screenshot.

**Comment by felangel** [comment] 2024-08-28 20:33
> Nope, just verified that generating a Microsoft token and setting it as an env variable as per the instructions does not print the warning displayed in the screenshot.

Sorry meant to tag the customer not you 🤣

**Comment by rafaelfernandesx** [comment] 2024-08-29 11:55
> @rafaelfernandesx you mentioned in the other comment that you're base-64 encoding the token. You should not do this—the token is already encoded.

Yes, I tested encoding in base64 and in this print I did it without encoding, just copying the token from the console and pasting it into codemagic.
![image](https://github.com/user-attachments/assets/c0d670c0-0196-4b5d-acbe-849dd362cf9a)

<img width="2290" alt="image" src="https://github.com/user-attachments/assets/2530918d-1c5d-4e57-8cb3-70d082c4020d">

**Comment by rafaelfernandesx** [comment] 2024-08-29 12:23
Apparently the problem is with my Microsoft corporate account, which does not have any permissions, displaying this error: "AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance."

Is it possible to change the login method from Microsoft to Google and continue with the shorebird account?

**Comment by rafaelfernandesx** [comment] 2024-08-29 13:08
I made a new account using the Google authentication method and it worked, so there is probably something in my corporate Microsoft account that was preventing it.

**Comment by bryanoltman** [comment] 2024-08-29 14:16
I can definitely help you out with that. Would you mind PMing me your details on Discord?

**Comment by rafaelfernandesx** [comment] 2024-08-29 14:28
No, my discord: rafaelfernandesx

**Comment by bryanoltman** [comment] 2024-08-29 14:32
Friend request sent. Closing this issue as we're moving to Discord.

**Closed as completed by bryanoltman** 2024-08-29 14:32 UTC
