### ISSUE TITLE
feat: Make it possible to "revert" from the console

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2193] opened 2024-06-03 19:42 UTC
Users sometimes expect to be able to "revert" a patch from the console.

There are a few layers to this:
1. Stop serving the existing patch.
2. Potentially make a copy of the patch N-1 as a new patch N+1
3. Teach updater how to un-install patch N when instructed by the server?

We'd have to decide exactly how we want to implement it.

**Comment by erickzanardo** [comment] 2024-06-11 13:10
@eseidel isn't this something that we already support? When I got to the console, on the patch list, I have an option to disable an patch.

![Screenshot 2024-06-11 at 10 09 30](https://github.com/shorebirdtech/shorebird/assets/835641/c361652e-fd80-4667-b72a-552593828e65)

**Comment by felangel** [comment] 2024-06-11 14:43
> @eseidel isn't this something that we already support? When I got to the console, on the patch list, I have an option to disable an patch.
> 
> ![Screenshot 2024-06-11 at 10 09 30](https://private-user-images.githubusercontent.com/835641/338595741-c361652e-fd80-4667-b72a-552593828e65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTcyNjgsIm5iZiI6MTcxODExNjk2OCwicGF0aCI6Ii84MzU2NDEvMzM4NTk1NzQxLWMzNjE2NTJlLWZkODAtNDY2Ny1iNzJhLTU1MjU5MzgyOGU2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxNDQyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODc1Zjg1NmRjYzMxZmQ2NjAxZDhiZGM4ZGY0YzRjZTk0OGU1NTFmZGUyMzliMGMwZjJhNGMyMjliYTQwMDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3m_jeM8Kuywse3K_v7xbIr6Cw1fra9JwYXm1nLyaFD0)

That will only stop serving the patch, it won’t actually revert the patch on devices which have installed the patch already.

**Comment by erickzanardo** [comment] 2024-06-11 15:56
Ah, got ya! Make sense then!

**Comment by bryanoltman** [comment] 2024-06-24 14:37
I think this might be a duplicate of https://github.com/shorebirdtech/shorebird/issues/126

**Closed as completed** 2024-06-24 14:39 UTC
Labels: enhancement
