### ISSUE TITLE
fix: shorebird preview might use wrong cached release

### ISSUE THREAD

**Issue by erickzanardo** [shorebirdtech/shorebird#1933] opened 2024-04-18 17:42 UTC
App ID: 1f375832-2444-4acc-9da9-3e486084c4de

**Description**

If you create a release, preview it, then delete it on the console, create a new release with the same version. Try to preview it, the installed version will be the deleted one and not the more recent

**Steps To Reproduce**

1. Create a release
2. Preview it
3. Delete the release in the console
4. Create a new release
5. Preview it
6. See the deleted release being installed

**Expected Behavior**

The last release should be the one installed

**Comment by felangel** [comment] 2024-04-25 17:10
We could use the hash of the aab as the file name instead of release version to address this or even just append to the existing file name to keep it somewhat human-readable 🤷

**Comment by bryanoltman** [comment] 2024-05-29 20:25
Duplicate of https://github.com/shorebirdtech/shorebird/issues/1746. Closing in favor of that

**Closed as completed by bryanoltman** 2024-05-29 20:25 UTC
Labels: bug
