### ISSUE TITLE
fix: Android after patch shared preferences lost data

### ISSUE THREAD

**Issue by elizacloud** [shorebirdtech/shorebird#1634] opened 2024-01-16 12:03 UTC
Is it normal for data to be lost in shared preferences after a patch update?

**Comment by bryanoltman** [comment] 2024-01-16 15:00
This is not expected and sounds like it could be a bug. Does this happen regularly?

**Comment by bryanoltman** [comment] 2024-01-16 16:03
I'm unable to reproduce this with a demo app using the following steps:

1. Create app using `flutter create`
2. Add the shared_preferences package
3. Store the counter value in shared prefs
4. Create and apply a patch

After doing this, the app loads the counter to the number that was set before the patch was applied.

**Comment by bryanoltman** [comment] 2024-01-16 20:24
If you're seeing this after using `shorebird preview`, this is expected, as the preview command reinstalls the app on the target device. I'm going to close this for now, but if you see this issue outside of shorebird preview and can share reproduction steps, we'd love to help

**Closed as completed by bryanoltman** 2024-01-16 20:24 UTC
Labels: bug

**Comment by eseidel** [comment] 2024-01-16 20:41
It is slightly confusing that `shorebird preview` on Android clears state (does a full re-install), but `shorebird preview` on iOS does not.

**Comment by felangel** [comment] 2024-01-16 22:21
> It is slightly confusing that `shorebird preview` on Android clears state (does a full re-install), but `shorebird preview` on iOS does not.

iOS does a full reinstall as well when using `ios-deploy` need to check devicectl though
https://github.com/shorebirdtech/shorebird/blob/d6fd43b386c12f173c7fbed06df8c790291d3460/packages/shorebird_cli/lib/src/executables/ios_deploy.dart#L163
