### ISSUE TITLE
fix: Patch on android taking a long time.

### ISSUE THREAD

**Issue by GabrielArtioli** [shorebirdtech/shorebird#2605] opened 2024-11-05 15:47 UTC
App ID:  br.com.unoerp.unoerp_app

**Steps To Reproduce**

Using shorebird patch android is taking too long, when I started to use Shorebird it usually took 15 minutos to patch, but now it's taking over 1h and it finishes with failure 

I excpect it to take a few minutes, it's almost taking the same time play store aprove the new version

![imagem_2024-11-05_124550011](https://github.com/user-attachments/assets/ed0fd38b-c6e3-4e9c-9df7-b91e3fde1b26)

[Uploading 1730817371409_shorebird.log…]()

**Comment by bryanoltman** [comment] 2024-11-05 17:14
This is a known issue https://github.com/shorebirdtech/shorebird/issues/2532. There are a few workaround listed in that bug, I'd be curious to hear whether any of them work for you. You can respond there, I'm going to close this one as a duplicate.

**Closed as completed by bryanoltman** 2024-11-05 17:14 UTC
Labels: bug

**Comment by eseidel** [comment] 2024-11-05 17:25
As noted in the other bug, the issue appears to be caused by Windows Defender getting confused by Dart's http implementation.  This seems to be a recent regression with Windows Defender and may have been patched in the most recent Microsoft Security update.
