### ISSUE TITLE
feat: support for Windows, MacOS and Linux

### ISSUE THREAD

**Issue by anderscheow** [shorebirdtech/shorebird#1415] opened 2023-10-19 08:16 UTC
**Description**

Since Flutter is getting more popular on desktop platforms (Windows, MacOS and Linux), it's great if Shorebird can provide support to desktop platforms. 

**Requirements**

- [ ] Windows platform
- [ ] MacOS platform
- [ ] Linux platform

**Comment by bryanoltman** [comment] 2023-10-20 15:35
This is a duplicate of https://github.com/shorebirdtech/shorebird/issues/397, closing in favor of the existing issue

**Closed as completed by bryanoltman** 2023-10-20 15:35 UTC
