### ISSUE TITLE
feat: Shorebird Preview with a different keystore file.

### ISSUE THREAD

**Issue by superakabo** [shorebirdtech/shorebird#2450] opened 2024-08-28 13:17 UTC
**Description**
Some app functionalities break when you decide to preview a shorebird release using the "shorebird preview" command. The process uses the default Flutter keystore without an option to provide the preferred keystore file to use. Apps that use APIs and services secured by a specific keystore fingerprint do not work as intended.

**Comment by bryanoltman** [comment] 2024-08-28 13:59
Duplicate of https://github.com/shorebirdtech/shorebird/issues/2113

**Closed as completed by bryanoltman** 2024-08-28 13:59 UTC
