### ISSUE TITLE
fix: rust updater error on iOS preview

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#971] opened 2023-08-01 20:18 UTC
Updater error on iOS preview

```
$ shorebird preview                                
✓ Fetching apps (0.2s)
Which app would you like to preview? flavors (stable)
✓ Fetching releases (81ms)
Which release would you like to preview? 1.0.0+1
Which platform would you like to preview? ios
✓ Started app (24.4s)
2023-08-01 15:16:51.547510-0500 Runner[37495:2239977] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-08-01 15:16:51.547571-0500 Runner[37495:2239977] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-08-01 15:16:51.547595-0500 Runner[37495:2239977] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-08-01 15:16:51.547617-0500 Runner[37495:2239977] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-08-01 15:16:51.547640-0500 Runner[37495:2239977] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-08-01 15:16:51.547680-0500 Runner[37495:2239977] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-08-01 15:16:51.560505-0500 Runner[37495:2239977] SANITY CHECK: Running precompiled code.
2023-08-01 15:16:51.560833-0500 Runner[37495:2239977] Using App.framework from /private/var/containers/Bundle/Application/9966FBED-6C07-4D6D-B9D9-903D0880E9DC/ios_1.0.0+1.app/Frameworks/App.framework
2023-08-01 15:16:51.561206-0500 Runner[37495:2239977] ASSET PATH /private/var/containers/Bundle/Application/9966FBED-6C07-4D6D-B9D9-903D0880E9DC/ios_1.0.0+1.app/Frameworks/App.framework/flutter_assets
[00:00:00.002] (21378f6c0) WARN   Slot 0 is invalid, clearing.
[00:00:00.003] (21378f6c0) WARN   Error while validating state: create_dir_all: Operation not permitted (os error 1), clearing state.
2023-08-01 15:16:51.567979-0500 Runner[37495:2239977] [VERBOSE0:shorebird.cc(96)] Shorebird updater: no active patch.
2023-08-01 15:16:51.567999-0500 Runner[37495:2239977] [VERBOSE0:shorebird.cc(99)] Starting Shorebird update
2023-08-01 15:16:51.568118-0500 Runner[37495:2239977] [VERBOSE0:FlutterViewController.mm(231)] CPU::Id(): simarm64
[00:00:00.003] (16dd0b000) WARN   Slot 0 is invalid, clearing.
[00:00:00.003] (16dd0b000) WARN   Error while validating state: create_dir_all: Operation not permitted (os error 1), clearing state.
2023-08-01 15:16:51.688228-0500 Runner[37495:2239977] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
2023-08-01 15:16:51.717114-0500 Runner[37495:2239977] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-08-01 15:16:51.717182-0500 Runner[37495:2239977] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-08-01 15:16:51.717210-0500 Runner[37495:2239977] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-08-01 15:16:51.717232-0500 Runner[37495:2239977] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
[00:00:06.543] (16dd0b000) INFO   Patch 2 successfully installed.
[00:00:06.543] (16dd0b000) INFO   Update thread finished with status: Update installed
```

**Comment by bryanoltman** [comment] 2023-09-13 18:53
I think this is a duplicate of https://github.com/shorebirdtech/shorebird/issues/1184. Closing in favor of that issue.

**Closed as completed by bryanoltman** 2023-09-13 18:53 UTC
Labels: bug
