### ISSUE TITLE
fix(dart-sdk): vmspecific_native_finalizer_isolate_groups_test

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#1549] opened 2023-12-05 16:50 UTC
**Description**

Need to fix the `ffi/vmspecific_native_finalizer_isolate_groups_test` failure.

**Steps To Reproduce**

` python3 tools/test.py -m release -c dartkp -r dart_precompiled -a arm64 --mixed-mode ffi/vmspecific_native_finalizer_isolate_groups_test`

```
Loading failed: Expected little-endian ELF object.
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: The uri provided to `Isolate.spawnUri()` does not contain a valid AOT snapshot.
```

**Expected Behavior**

Test passes

**Comment by eseidel** [comment] 2023-12-05 16:52
Duplicate of https://github.com/shorebirdtech/_shorebird/issues/476.

**Closed as completed by eseidel** 2023-12-05 16:52 UTC
Labels: bug
