### ISSUE TITLE
fix: Issues with Shorebird Patch Command Using Incorrect Flutter Version in GitHub Workflow

### ISSUE THREAD

**Issue by JedTsai33** [shorebirdtech/shorebird#2118] opened 2024-05-17 02:32 UTC
I am using Shorebird in a GitHub workflow. First, I install the latest version with the action:
```
- name: 🐦 Setup Shorebird
  uses: shorebirdtech/setup-shorebird@v1
```
Then, I generate an APK with version 3.19.0:

`shorebird release android --flutter-version=3.19.0`

However, when I subsequently run `shorebird patch android`, I encounter an error:
```
⠋ Building patch with Flutter 3.22.0 (6d047e4019)...
✗ Failed to build: Flutter assets will be downloaded from https://download.shorebird.dev. Make sure you trust this source!
```
According to [the documentation](https://docs.shorebird.dev/flutter-version/), it should automatically use the same Flutter version as the release, but it doesn't seem to be doing so. Currently, it's not possible to use the shorebird flutter versions use command. Do you have any suggested solutions for this issue?

**Comment by felangel** [comment] 2024-05-17 05:22
Hi @JedTsai33 👋 
This is a duplicate of https://github.com/shorebirdtech/shorebird/issues/1945. Shorebird needs to build your app to determine the release version so it'll use the latest stable version to build your app, detect the release version, and then re-build using the same version used to build the release. You can bypass the initial build by specifying the release version to use:

```
shorebird patch android --release-version=1.0.0+1
```

Instead of 1.0.0+1 be sure to specify the correct release version of your app. Hope that helps and apologies for the inconvenience!

**Comment by JedTsai33** [comment] 2024-05-17 08:32
Sorry for not realizing it was a duplicate issue.
Testing with `--release-version` works fine.
Thank you for your assistance.

**Closed as completed** 2024-05-17 14:11 UTC
Labels: duplicate
