### ISSUE TITLE
fix: bad output from validation failure?

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#357] opened 2023-04-24 19:01 UTC
```eseidel@erics-mbp test_app % ../_shorebird/shorebird/bin/shorebird --local-engine-src-path=~/Documents/GitHub/engine/src --local-engine=android_arm64_release run
Unhandled exception:
Instance of 'FlutterValidationException'
#0      ShorebirdFlutterValidator._getFlutterVersion (package:shorebird_cli/src/validators/shorebird_flutter_validator.dart:139:7)
<asynchronous suspension>
#1      ShorebirdFlutterValidator.validate (package:shorebird_cli/src/validators/shorebird_flutter_validator.dart:58:37)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      ShorebirdValidationMixin.logValidationIssues (package:shorebird_cli/src/flutter_validation_mixin.dart:8:31)
<asynchronous suspension>
#4      RunCommand.run (package:shorebird_cli/src/commands/run_command.dart:36:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:131:18)
<asynchronous suspension>
#7      ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:92:14)
<asynchronous suspension>
#8      main (file:///Users/eseidel/Documents/GitHub/_shorebird/shorebird/packages/shorebird_cli/bin/shorebird.dart:6:24)
<asynchronous suspension>
```

I suspect my command line arg is wrong, but it could fail better I think?

**Comment by felangel** [comment] 2023-04-24 19:25
I think this might be a duplicate of #337

**Comment by eseidel** [comment] 2023-04-24 19:36
Yeah, there are two places which throw a FlutterValidationException, but no places which catch one.  Presumably the mixin is supposed to do that?  @bryanoltman said he could take a look.

**Closed as completed** 2023-04-24 20:18 UTC
Labels: bug
