### ISSUE TITLE
fix: Cloud signing permission error

### ISSUE THREAD

**Issue by Fudal** [shorebirdtech/shorebird#1164] opened 2023-08-25 07:56 UTC
**Description**

**Steps To Reproduce**

`shorebird release ios-alpha 
`
**Expected Behavior**

Build release 

**Additional Context**

When I build the iOS version in xCode, I have to manually select a profile for signing. Admittedly, I only have one profile in the list, but checking to sign automatically doesn't work, so I have to select it manually.
![Zrzut ekranu 2023-08-25 o 09 48 37](https://github.com/shorebirdtech/shorebird/assets/13346676/5dc32310-0105-40a8-a2a2-df14e5cdfba4)

Consequently, it does not work to build the release for ios-alpha because the signing profile is not indicated.

Is there any way I can remedy this?

**Comment by bryanoltman** [comment] 2023-08-25 14:08
I believe this is a duplicate of https://github.com/shorebirdtech/shorebird/issues/1067. Going to close this and move the conversation there.

**Closed as completed by bryanoltman** 2023-08-25 14:08 UTC
Labels: bug
