### ISSUE TITLE
fix: shorebird release ios does not recognize the profiles in Codemagic.

### ISSUE THREAD

**Issue by Segatti** [shorebirdtech/shorebird#1889] opened 2024-04-11 00:48 UTC
App ID: a46deb1e-6f5b-447a-8f42-da816751bc33

**Description**

**I'm with the following shorebird configuration file:**

```
workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: --.---.------------
      groups:
        - app_aluno
        - shorebird
      vars:
        APP_STORE_APPLE_ID: -------------
      flutter: 3.16.9
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create files secrets
        script: |
          #!/bin/sh
          echo $ENV_ALUNO | base64 --decode > $CM_BUILD_DIR/.env
          echo $FIREBASE_IOS_ALUNO | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
          echo $FIREBASE_ANDROID_ALUNO | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
      - name: 🐦 Setup Shorebird
        script: |
          # Install Shorebird
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

          # Add Shorebird to PATH
          echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Clear cache Flutter
        script: |
          flutter pub cache clean -f
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: false
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: false
      - name: 🚀 Shorebird Release
        script: shorebird release ios
      # - name: Flutter build ipa and automatic versioning
      #   script: |
      #     flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - "email"
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      slack:
        channel: "#opd-devops-notification"
        notify_on_build_start: false
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - "Testers Interno"
        submit_to_app_store: false
```

**And I'm receiving the following error in codemagic:**

```
⠋ Fetching apps...
✓ Fetching apps (0.3s)
⠋ Building release with Flutter 3.19.5 (25bc2b57a1)...
✗ Failed to build (204.5s)
    No Accounts
    No profiles for '_.__.___.TimerLiveActivity' were found
    No profiles for '_.__.___.HomeWidget' were found
    No profiles for '_.__.___' were found

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.


Build failed :|
Step 12 script `🚀 Shorebird Release` exited with status code 70
```
**This only happens with iOS on shorebird, if I generate a normal version, this error does not occur.**

**Steps To Reproduce**

1. run 'shorebird release ios' in codemagic
2. See error

**Expected Behavior**

I hope to be able to compile successfully.

**Additional Context**

I use app extensions for Home Widget and Live Activity.

**Comment by eseidel** [comment] 2024-04-11 17:19
This seems to relate to XCode signing.  I don't know a lot about setting that up on CodeMagic, but looks like they have docs:
https://docs.codemagic.io/flutter-code-signing/ios-code-signing/

**Comment by eseidel** [comment] 2024-04-17 21:05
We would love to help. I'm not sure if there is anything more for us to do though?  Let us know if you're still blocked.  Speculatively closing for now.

**Closed as completed by eseidel** 2024-04-17 21:05 UTC
Labels: bug

**Comment by Abdelazeem777** [comment] 2024-07-10 19:09
@eseidel 
I am facing the same issue but with github actions

here is my logs:

```
Run shorebirdtech/shorebird-release@v0
Run shorebird release ios --flutter-version=3.22.2 | tee output.log
⠋ Fetching apps...
✓ Fetching apps (0.2s)
⠋ Building ipa with Flutter 3.22.2 (f32fc7841e)...
✗ Failed to build:
    No Accounts
    No profiles for 'com.taxiapp.rider.taxiAppRider.NotificationService' were found
    No Accounts
    No profiles for 'com.taxiapp.rider.taxiAppRider' were found (846.4s)

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also ]8;;https://github.com/shorebirdtech/shorebird/issues/new/choose\file an issue]8;;\ if you think this is a bug. Please include the following log file in your report:
/Users/runner/Library/Application Support/shorebird/logs/17206364260[31](https://github.com/Rasan-Al-Arabia/taxi_rider_app/actions/runs/9785778647/job/27019435682#step:11:33)_shorebird.log

Error: Process completed with exit code 70.
```

**Comment by Jonny1987** [comment] 2024-08-29 16:56
I have the same issue and these were the causes:
1) my "distribution_type" was "app_store" but I didn't have a 'distribution' provisioning profile in my apple developer account
2) I needed to include `--export-options-plist=/Users/builder/export_options.plist` in my shorebird command

**Comment by Segatti** [comment] 2024-09-08 20:11
I finally did it!! I checked the documentation again to see if it had been updated, and now it's working. It takes a bit of effort to set up, but it was worth it. Link: https://docs.shorebird.dev/ci/codemagic . I only made one modification because I wasn't sure if the documentation was wrong, as it was missing the use of the "CERTIFICATE_PRIVATE_KEY" variable. So, I added it to the script as well.

Here’s my modified version of the script:

> #Codemagic
      - &fetch_signing_files
      name: Fetch signing files
      script: |
        app-store-connect fetch-signing-files "$BUNDLE_ID" \
          --type IOS_APP_STORE --create \
          --issuer-id "$ISSUER_ID" \
          --key-id "$KEY_ID" \
          --certificate-key "$CERTIFICATE_PRIVATE_KEY" \
          --private-key="$APP_STORE_CONNECT_PRIVATE_KEY"

**Comment by rmilejcz** [comment] 2024-09-18 14:37
EDIT: The fix for this issue in most likely all contexts is to manually create your own `export_options.plist` file, and forward it to shorebird: `shorebird release ios -- --export_options_plist=./export_options.plist`. In my case, the file looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>
    <string>ad-hoc</string>
    <key>provisioningProfiles</key>
    <dict>
        <key>com.MYAPP.IDENTIFIER</key>
        <string>MY PROVISIONING PROFILE NAME</string>
    </dict>
</dict>
</plist>
```

If your app is onthe app store (mine is not) you would use `app-store` instead of `ad-hoc`. After implementing this, shorebird is able to properly output an IPA for me to release. I would recommend adding this to your generic CI instructions, or a troubleshooting section, to prevent confusion moving forward

-----------

I am having this issue in Bitrise. I am able to build the app using `flutter build ipa` without issue but when I switch to `shorebird release ios` xcode fails to find my profile and sign the app.

I have run shorebird doctor, no issues, and also verified that the profile and certificate are available in the context that `shorebird release ios` is being run in, still no luck.

Tried both manual and automatic signing configurations still no luck.

Irrespective of shorebird I am able to build the app, but for some reason I cannot get shorebird to recognize my valid and present certificate and profiles. My only thought is that my app distribution method is causing some issue with shorebird's underlying logic (it is Ad Hoc). But I can't find any information to help me proceed, so am I reviving this old issue.

As per the docs `shorebird release wraps flutter build`, but these commands are not interchangeable in my environment.
