### ISSUE TITLE
Add example update UI for Flutter.

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#124] opened 2023-03-21 21:08 UTC
Some apps may want to show a UI to assist with the download (asynchronously).  Play store lists this as a common error (although it's not clear that apps actually follow this guideline in the wild, I've rarely seen it):
"Apps with content delivery network (CDN) facilitated downloads that fail to prompt the user and disclose the download size prior to downloading."
https://support.google.com/googleplay/android-developer/answer/9888077?hl=en#zippy=%2Cexamples-of-common-violations

**Comment by eseidel** [comment] 2023-03-21 21:18
Duplicate of https://github.com/shorebirdtech/shorebird/issues/80

**Closed as completed by eseidel** 2023-03-21 21:18 UTC
