### ISSUE TITLE
feat: Ability to download specified patch using patch number

### ISSUE THREAD

**Issue by canewsin** [shorebirdtech/shorebird#2099] opened 2024-05-15 05:11 UTC
**Description**

Not all patches are meant to be downloaded by all the users, currently we can only download latest patch. Currently i was using trigger pattern to download patch when necessary.

**Comment by bryanoltman** [comment] 2024-05-15 13:59
I believe this is a duplicate of https://github.com/shorebirdtech/shorebird/issues/461. Please reopen if I'm misunderstanding.

**Closed as completed by bryanoltman** 2024-05-15 13:59 UTC
