### ISSUE TITLE
Update the patch changes in the apk installed from the store or from the apk link shared with user

### ISSUE THREAD

**Issue by mansigupta07091998** [shorebirdtech/shorebird#2506] opened 2024-10-02 18:59 UTC
Suppose I have shared one apk with user and the I made some changes in code then those changes will come to the user who have installed the apk by relaunching the app, but if the user uninstalls the apk and again install the same apk then the changes which I have done using the patch is not visible for the first time again the user has to relaunch the app...why so and how this can be fixed

**Comment by bryanoltman** [comment] 2024-10-02 19:10
This is because patches are stored as files in the app's cache directory. These files are deleted when the app is deleted, meaning they need to be redownloaded when the app is uninstalled and reinstalled.

**Comment by bryanoltman** [comment] 2024-10-02 19:10
Closing as "working as intended"

**Closed as completed by bryanoltman** 2024-10-02 19:10 UTC

**Comment by eseidel** [comment] 2024-10-02 19:13
I would be possible to block the user from using the app until it's updated, but Shorebird has no way to change what's sent to the user from the Stores (short of you making a new Release to the stores).  As Bryan notes, when the app is uninstalled, the patches are all un-installed, and won't be installed again until the user has launched the app (since Shorebird can only run code inside your app).

**Comment by mansigupta07091998** [comment] 2024-10-02 19:22
Can this be possible that when user installs the app then starts logging in, then only the patch changes gets installed and when user move on homescreen or any other screen then those changes gets visible..means will the changes gets visible without relaunching the app in case of fresh install of the apk?

**Comment by eseidel** [comment] 2024-10-02 19:28
Currently re-launching the app is required.   This is due to how difficult it can be to not confuse the non-dart parts of the app, when the Dart parts suddenly restart.  We definitely could do something here, but don't currently offer a restart-less flow: https://github.com/shorebirdtech/shorebird/issues/2350
